// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: Smartwatch

#include "../ui.h"

// COMPONENT dategroup

lv_obj_t * ui_dategroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dategroup;
    cui_dategroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_dategroup, 100);
    lv_obj_set_height(cui_dategroup, 82);
    lv_obj_set_x(cui_dategroup, 58);
    lv_obj_set_y(cui_dategroup, 53);
    lv_obj_set_align(cui_dategroup, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_dategroup, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_dategroup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(cui_dategroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_dategroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dategroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    //lv_obj_t * cui_day;
    ui_day1 = lv_label_create(cui_dategroup);
    lv_obj_set_width(ui_day1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_day1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day1, "MON");
    lv_obj_set_style_text_color(ui_day1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day1, &ui_font_Subtitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    //lv_obj_t * cui_month;
    ui_month1 = lv_label_create(cui_dategroup);
    lv_obj_set_width(ui_month1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_month1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month1, "18 FEB");
    lv_obj_set_style_text_color(ui_month1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_month1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_month1, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

//    lv_obj_t * cui_year;
    ui_year1 = lv_label_create(cui_dategroup);
    lv_obj_set_width(ui_year1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_year1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year1, "2022");
    lv_obj_set_style_text_color(ui_year1, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year1, &ui_font_Title, LV_PART_MAIN | LV_STATE_DEFAULT);

//    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DATEGROUP_NUM);
//    children[UI_COMP_DATEGROUP_DATEGROUP] = cui_dategroup;
//    children[UI_COMP_DATEGROUP_DAY] = ui_day1;
//    children[UI_COMP_DATEGROUP_MONTH] = ui_month1;
//    children[UI_COMP_DATEGROUP_YEAR] = ui_year1;
//    lv_obj_add_event_cb(cui_dategroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
//    lv_obj_add_event_cb(cui_dategroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
//    ui_comp_dategroup_create_hook(cui_dategroup);
    return cui_dategroup;
}

